# Generated by Django 4.2.27 on 2026-01-19 20:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default=accounts.models.generate_referral_code, editable=False, max_length=8, null=True, verbose_name='Codigo de referido'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_goal',
            field=models.PositiveIntegerField(default=10, verbose_name='Meta de referidos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referido por'),
        ),
    ]
