# Generated by Django 4.2.27 on 2026-01-19 20:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_referral_codes'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to avoid SQLite table recreation issue
        # The database already has the data with unique values from 0003
        # We just need Django to know the field is now unique
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='customuser',
                    name='referral_code',
                    field=models.CharField(
                        default=accounts.models.generate_referral_code,
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name='Codigo de referido'
                    ),
                ),
            ],
            database_operations=[
                # Create unique index directly on existing column
                migrations.RunSQL(
                    sql='CREATE UNIQUE INDEX IF NOT EXISTS "accounts_customuser_referral_code_uniq" ON "accounts_customuser" ("referral_code");',
                    reverse_sql='DROP INDEX IF EXISTS "accounts_customuser_referral_code_uniq";',
                ),
            ],
        ),
    ]
