# Generated by Django 4.2.27 on 2026-01-20 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_referral_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('ACTIVE', 'Activo'), ('NOT_FOUND', 'No encontrado'), ('CANCELLED_DECEASED', 'Cancelada - Fallecido'), ('CANCELLED_OTHER', 'Cancelada - Otro'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('puesto', models.CharField(blank=True, max_length=200, verbose_name='Puesto de votacion')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Direccion')),
                ('mesa', models.CharField(blank=True, max_length=20, verbose_name='Mesa')),
                ('novedad', models.CharField(blank=True, max_length=200, verbose_name='Novedad')),
                ('resolucion', models.CharField(blank=True, max_length=100, verbose_name='Resolucion')),
                ('fecha_novedad', models.CharField(blank=True, max_length=50, verbose_name='Fecha de novedad')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de consulta')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('raw_response', models.TextField(blank=True, help_text='HTML/JSON response from Registraduria for debugging', verbose_name='Respuesta cruda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_info', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Informacion de cedula',
                'verbose_name_plural': 'Informacion de cedulas',
            },
        ),
    ]
