# Generated by Django 4.2.27 on 2026-01-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cedulainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('LEADER', 'Lider')], default='USER', max_length=10, verbose_name='Rol'),
        ),
    ]
