# Generated by Django 4.2.27 on 2026-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedulainfo',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos'),
        ),
    ]
